name: Build Windows

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-windows.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-windows.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  build-windows:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        windows: [windows-2019, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.windows }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.7.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat build-release msi
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
    # Artifact name
            #name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
            path: out
    # The desired behavior if no files are found using the provided path.
